### ISSUE TITLE
When displaying forward rate for a generic expression change, the generic expression needs to be displayed instead of a label saying genericexpression

### ISSUE THREAD

**Issue by adrianq** [NeuroML/org.neuroml.export#18]
Cerebellar Granule Cell Schutter > gateH

http://opensourcebrain.org/projects/grancelllayer?explorer=https%3A%2F%2Fraw.github.com%2FOpenSourceBrain%2FGranCellLayer%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FGolgi_CaHVA_CML.channel.nml#

**Comment by pgleeson** [comment]
Out of date
