### ISSUE TITLE
List of LEMS/NML2 examples that can't be exported to neuron

### ISSUE THREAD

**Issue by borismarin** [NeuroML/org.neuroml.export#41]
Problems with `.mod` file generation/compilation:
- [x] LEMS_NML2_Ex1_HH.xml
- [x] LEMS_NML2_Ex3_Net.xml
- [x] LEMS_NML2_Ex6_NMDA.xml
- [x] LEMS_NML2_Ex7_STP.xml
- [x] LEMS_NML2_Ex10_Q10.xml
- [x] LEMS_NML2_Ex12_Net2.xml
- [x] LEMS_NML2_Ex15_CaDynamics.xml
- [ ] LEMS_NML2_Ex17_Tissue.xml

**Comment by pgleeson** [comment]
All of these now work with Neuron and have tests (in the [development branch](https://github.com/NeuroML/NeuroML2/tree/development/LEMSexamples)), apart from Ex17, whose main feature, changing the temperature mid simulation is outside of the scope of the Neuron mapping currently (could be added later if anyone has a usecase...)
