### ISSUE TITLE
Weighted synapses in Ex21 are not exported correctly to neuron

### ISSUE THREAD

**Issue by borismarin** [NeuroML/org.neuroml.export#42]
This is the reason LEMS_NML2_Ex21_CurrentBasedSynapses.xml does not work.
- generated `alphaSyn.mod` doesn't correctly expose "i" (try renaming state variable to sthing else)
-  generated `LEMS_NML2_Ex21_CurrentBasedSynapses_nrn.py` does not correctly set the weight for the NetCon (last arg should be 5e-11 instead of 0).

**Comment by pgleeson** [comment]
Closed @borismarin?

**Comment by borismarin** [comment]
closed by https://github.com/NeuroML/org.neuroml.export/pull/43
