### ISSUE TITLE
NeuronWriter does not create unidirectional gap junctions?

### ISSUE THREAD

**Issue by lungd** [NeuroML/org.neuroml.export#57]
I have a nml file with 1 GJ (between AVBR and DB1)
```
<gapJunction id="neuron_to_neuron_elec_syn_15conns" conductance="0.3378nS"/>
...
<electricalProjection id="NC_AVBR_DB1_Generic_GJ" presynapticPopulation="AVBR" postsynapticPopulation="DB1">
    <electricalConnectionInstance id="0" preCell="../AVBR/0/GenericNeuronCell" preSegment="0" preFractionAlong="0.5" postCell="../DB1/0/GenericNeuronCell" postSegment="0" postFractionAlong="0.5" synapse="neuron_to_neuron_elec_syn_15conns"/>
</electricalProjection>
```
`pynml LEMS_c302_C2_AVB_DB.xml -neuron` creates the ..._nrn.py file with following content:
```
# ######################   Electrical Projection: NC_AVBR_DB1_Generic_GJ
print("Adding electrical projection: NC_AVBR_DB1_Generic_GJ from AVBR to DB1, with 1 connection(s)")

h("objectvar syn_NC_AVBR_DB1_Generic_GJ_neuron_to_neuron_elec_syn_15conns_A[1]")
h("objectvar syn_NC_AVBR_DB1_Generic_GJ_neuron_to_neuron_elec_syn_15conns_B[1]")

# Elect Connection 0: cell 0, seg 0 (0.5) [0.5 on a_AVBR[0].soma] -> cell 0, seg 0 (0.5) [0.5 on a_DB1[0].soma], weight: 1.0
h("a_AVBR[0].soma { syn_NC_AVBR_DB1_Generic_GJ_neuron_to_neuron_elec_syn_15conns_A[0] = new neuron_to_neuron_elec_syn_15conns(0.5) }")
h("a_DB1[0].soma { syn_NC_AVBR_DB1_Generic_GJ_neuron_to_neuron_elec_syn_15conns_B[0] = new neuron_to_neuron_elec_syn_15conns(0.5) }")
h("setpointer syn_NC_AVBR_DB1_Generic_GJ_neuron_to_neuron_elec_syn_15conns_A[0].vpeer, a_DB1[0].soma.v(0.5)")
h("setpointer syn_NC_AVBR_DB1_Generic_GJ_neuron_to_neuron_elec_syn_15conns_B[0].vpeer, a_AVBR[0].soma.v(0.5)")
```
Am I right that the result is a bidirectional GJ?

I got the expected output without the 'A' part. I did try to comment out the 'A' part after executing `pynml LEMS_c302_C2_AVB_DB.xml -neuron` and then `nrnivmodl && nrngui -python LEMS_c302_C2_AVB_DB_nrn.py` to check the output.

**Comment by pgleeson** [comment]
Yes, the correct behaviour for this is to create 2 electrical connections, one from cell A to cell B with conductance 0.3378nS, and one from cell B to cell A with the same conductance.

To make a unidirectional gap junction, you could just use a continuousProjection with one end silent and the other as a (custom) synapse which just depends on the pre/post v, see:
https://github.com/NeuroML/NeuroML2/blob/master/examples/NML2_AnalogSynapsesHH.nml
