### ISSUE TITLE
What does the value of 318.91927 represent in abstract cell CM?

### ISSUE THREAD

**Issue by JustasB** [NeuroML/org.neuroml.export#60]
There are [several spots](https://github.com/search?q=org%3ANeuroML+318.31927&type=Code) where the value of `318.31927` is used for abstract cell CM. The cells have L and Diam = 10.

The area of a cell with L,D=10 would be 314.1592, which is slightly different...

Is there something special about this CM value? I did not find any other mention of this number elsewhere.

**Comment by borismarin** [comment]
It is the second most important number in the universe, after 42, of course.

Actually, it comes from 1/pi and facilitates area/volume calculations.

Em Qua, 28 de mar de 2018 19:50, Justas Birgiolas <notifications@github.com>
escreveu:

**Comment by JustasB** [comment]
Ah, interesting... But, 1/PI*1000 is ~318.309, which is close but not quite the same. I do see the 1/PI value on this line: https://github.com/NeuroML/org.neuroml.export/blob/015815ee0779a018fc2f9cad1e6e9d15e04818f3/src/main/resources/pynn/abstract_cell.vm#L22

But the slightly different value is used at the very end of the line... Is it just copy-pasted a typo in those other lines?

**Comment by borismarin** [comment]
@pgleeson?

Em Qua, 28 de mar de 2018 20:25, Justas Birgiolas <notifications@github.com>
escreveu:
